Deck\Domain\Table\TableReadModel:
    type: entity
    repositoryClass: Deck\Infrastructure\Persistence\Repository\Table\DoctrineTableReadModelRepository
    table: tables
    schema: deck
    id:
        id:
            id: true
            type: table_id
    fields:
        players:
            type: players_id_array
