parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        driver: 'pdo_postgresql'
        server_version: '10.5'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_unicode_ci
        schema_filter: ~^(?!deck.sessions)~ #ignore those tables when generating migrations
        url: '%env(DATABASE_DB_TYPE)%://%env(DATABASE_USER)%:%env(DATABASE_PASSWORD)%@%env(DATABASE_DB_HOST)%:%env(DATABASE_PORT)%/%env(DATABASE_DB)%'
