jms_serializer:
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
    metadata:
        auto_detection: false
        directories:
            Domain:
                namespace_prefix: "Deck\\Domain"
                path: "%kernel.project_dir%/src/Infrastructure/Serializer/Mapping/Domain"
            Broadway:
                namespace_prefix: "Broadway\\EventSourcing"
                path: "%kernel.project_dir%/src/Infrastructure/Serializer/Mapping/Broadway"
