nelmio_api_doc:
    documentation:
        info:
            title: Deck ES
            description: Event sourcing deck
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: apiKey
                    description: 'Value: Bearer {jwt}'
                    name: Authorization
                    in: header
            schemas:
                Table:
                    type: object
                    properties:
                        id:
                            type: string
                User:
                    type: object
                    properties:
                        email:
                            type: string
                        password:
                            type: string
                Game:
                    type: object
                    properties:
                        id:
                            type: string
        security:
            - Bearer: []
        paths:
            /api/login_check:
                post:
                    summary: Get jwt
                    requestBody:
                        required: true
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        username:
                                            type: string
                                        password:
                                            type: string
                    tags:
                        - Security
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
