security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders:
        bcrypt:
            algorithm: bcrypt
            cost: 12

    providers:
        user_provider:
            id: Deck\Infrastructure\User\Auth\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            provider: user_provider
            anonymous: ~
            guard:
                entry_point: 'Deck\Infrastructure\User\Auth\Guard\LoginAuthenticator'
                authenticators:
                    - 'Deck\Infrastructure\User\Auth\Guard\LoginAuthenticator'
            form_login:
                login_path: /sign-in
                check_path: sign-in
            logout:
                path: /logout
                target: /
            logout_on_user_change: true

    access_control:
        - { path: ^/profile/*, roles: ROLE_USER }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
