twig:
    paths:
        '%kernel.project_dir%/src/Infrastructure/Resources/views': DeckTwigTemplates
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']
