services:
    #FACTORIES
    game.factory.deck:
        class: Deck\Domain\Deck\DeckFactory

    game.factory.game:
        class: Deck\Domain\Game\GameFactory
        arguments: ['@game.factory.deck']

    #REPOSITORIES
    game.repository.game:
        class: Deck\Infrastructure\Persistence\Repository\Game\DoctrineGameRepository
        factory: ['@doctrine.orm.default_entity_manager', 'getRepository']
        arguments: ['Deck\App\Domain\Game\Game']

    game.create_new_game_handler:
        class: Deck\Application\Game\CreateGameHandler
        arguments: ['@game.factory.game']
        tags:
            - { name: command_handler, handles: Deck\Application\Game\CreateGameCommand }
