version: '3.7'

services:
  php:
    build:
      dockerfile: docker/dev/php/Dockerfile
      context: .
    container_name: deck-php
    expose:
      - 80
    ports:
      - 8080:80
    volumes:
      - .:/var/www/deck
    working_dir: /var/www/deck
    links:
      - deck_database
    environment:
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
      PHP_IDE_CONFIG: 'serverName=Dev'
      XDEBUG_REMOTE_HOST: 'docker.for.mac.host.internal'

  php_test:
    build:
      dockerfile: docker/dev/php/Dockerfile
      context: .
    container_name: deck-php-test
    volumes:
      - .:/var/www/deck
    working_dir: /var/www/deck
    links:
      - deck_database
    environment:
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
      PHP_IDE_CONFIG: 'serverName=Test'
      XDEBUG_REMOTE_HOST: 'docker.for.mac.host.internal'

  deck_database:
    image: postgres:9.6.6
    container_name: deck-database
    expose:
      - 5433
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=deck
    volumes:
      - database:/var/lib/postgresql/data

  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      # The standard AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'

volumes:
  database:
    driver: local
