version: '3.7'

services:
  php:
    build:
      dockerfile: docker/dev/php/Dockerfile
      context: .
    platform: linux/x86_64
    container_name: deck-php
    expose:
      - 80
    ports:
      - "8888:80"
    volumes:
      - .:/var/www/deck
    working_dir: /var/www/deck
    links:
      - postgresql
    environment:
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
      PHP_IDE_CONFIG: 'serverName=Dev'
      XDEBUG_REMOTE_HOST: 'docker.for.mac.host.internal'

  postgresql:
    image: postgres:9.6.6
    container_name: deck-database
    expose:
      - 5433
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=deck
    volumes:
      - database:/var/lib/postgresql/data

#  rabbitmq:
#    image: 'rabbitmq:3.6-management-alpine'
#    container_name: deck-rabbitmq
#    ports:
#      # The standard AMQP protocol port
#      - '5672:5672'
#      # HTTP management UI
#      - '15672:15672'

  api-doc:
    image: swaggerapi/swagger-ui:v3.52.3
    container_name: deck-api-doc
    restart: unless-stopped
    expose:
      - 8080
    ports:
      - "8889:8080"
    environment: [ "SWAGGER_JSON=/var/www/deck-api-doc/openapi.json","VALIDATOR_URL=" ]
    volumes:
      - ./spec:/var/www/deck-api-doc:ro

  pact-broker:
    image: 'pactfoundation/pact-broker:latest'
    platform: linux/x86_64
    container_name: deck-pact-broker
    depends_on:
      - postgresql
    ports:
      - "9292:9292"
    environment:
      PACT_BROKER_DATABASE_URL: 'postgres://admin:pass@postgresql/deck'
      PACT_BROKER_PORT: '9292'
      PACT_BROKER_LOG_LEVEL: INFO
      PACT_BROKER_SQL_LOG_LEVEL: DEBUG
      # PACT_BROKER_DATABASE_CONNECT_MAX_RETRIES is only needed for docker-compose
      # because the database takes longer to start up than the puma process
      # Should not be needed in production.
      PACT_BROKER_DATABASE_CONNECT_MAX_RETRIES: "5"
      # The list of allowed base URLs (not setting this makes the app vulnerable to cache poisoning)
      # This allows the app to be addressed from the host from within another docker container correctly
      PACT_BROKER_BASE_URL: 'https://localhost http://localhost http://localhost:9292 http://deck-pact-broker:9292'

#  pact-stub:
#    image: 'pactfoundation/pact-stub-server:latest'
#    platform: linux/x86_64
#    container_name: deck-pact-stub
#    expose:
#      - 8080
#    ports:
#      - "8080:8080"
#    volumes:
#      - ./pacts:/app/pacts:ro
#    command:
#      - '-dpacts'
#      - '-p8080'

volumes:
  database:
    driver: local
