Deck\Domain\User\ValueObject\Auth\Credentials:
  exclusion_policy: ALL
  properties:
    email:
      expose: true
      type: Deck\Domain\User\ValueObject\Email
    password:
      expose: true
      type: Deck\Domain\User\ValueObject\Auth\HashedPassword
