index:
    path: /
    controller: Deck\Infrastructure\Ui\Http\Controller\HomeController::index

sign-in:
    path: /sign-in
    controller: Deck\Infrastructure\Ui\Http\Controller\SecurityController:signIn

sign-up:
    path: /sign-up
    controller:  Deck\Infrastructure\Ui\Http\Controller\SecurityController:signUp

logout:
    path: /logout
    controller:  Deck\Infrastructure\Ui\Http\Controller\SecurityController:logout
