Deck\Domain\User\PlayerReadModel:
  type: entity
  repositoryClass: Deck\Infrastructure\Persistence\Repository\User\DoctrinePlayerReadModelRepository
  table: players
  schema: deck
  embedded:
    credentials:
      class: Deck\Domain\User\ValueObject\Auth\Credentials
  id:
    id:
      id: true
      type: player_id
  fields:
    createdAt:
      type: custom_datetime
    updatedAt:
      type: custom_datetime
      columnDefinition: TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
