Deck\Domain\User\ValueObject\Auth\Credentials:
  type: embeddable
  indexes:
    users_email_index:
      columns: [email]
  fields:
    email:
      type: string
      unique: true
    password:
      type: string
